//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DOT.g4 by ANTLR 4.5.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Antlr.DOT {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DOTParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.2")]
[System.CLSCompliant(false)]
public interface IDOTVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.graph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGraph([NotNull] DOTParser.GraphContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.stmt_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt_list([NotNull] DOTParser.Stmt_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] DOTParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.attr_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttr_stmt([NotNull] DOTParser.Attr_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.attr_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttr_list([NotNull] DOTParser.Attr_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.a_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitA_list([NotNull] DOTParser.A_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.edge_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdge_stmt([NotNull] DOTParser.Edge_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.edgeRHS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdgeRHS([NotNull] DOTParser.EdgeRHSContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.edgeop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdgeop([NotNull] DOTParser.EdgeopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.node_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNode_stmt([NotNull] DOTParser.Node_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.node_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNode_id([NotNull] DOTParser.Node_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.port"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPort([NotNull] DOTParser.PortContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.subgraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubgraph([NotNull] DOTParser.SubgraphContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DOTParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] DOTParser.IdContext context);
}
} // namespace Antlr.DOT
